apiVersion: v1
kind: ConfigMap
metadata:
  name: smf2-configmap
  labels:
    app: open5gs
    nf: smf
    name: smf2
data:
  smfcfg.yaml: |
    logger:
      file: /open5gs/install/var/log/open5gs/smf.log

    global:
      max:
        ue: 1024

    smf:
      sbi:
        server:
          - dev: eth0
            advertise: smf2-nsmf
            port: 80
        client:
          scp: 
            - uri: http://scp-nscp:80
      pfcp:
        server:
          - dev: n4
        client:
          upf:
            - address: 10.10.4.2
              dnn: streaming
      gtpc:
        server:
          - dev: eth0
      gtpu:
        server:
          - dev: n3
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      session:
        - subnet: 10.42.0.1/16
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
      ctf:
        enabled: auto
      freeDiameter: /open5gs/install/etc/freeDiameter/smf.conf

      info:
        - s_nssai:
          - sst: 2
            sd: 000002
            dnn:
             - streaming
