---
apiVersion: v1
kind: Service
metadata:
  name: ueransim-ue-churn
  labels:
    app: ueransim
    component: ue
    profile: churn
spec:
  clusterIP: None
  selector:
    app: ueransim
    component: ue
    profile: churn
